### ISSUE TITLE
Terra Settings Tracking

### ISSUE THREAD

**Issue by andyneff** [VisionSystemsInc/terra#26]
Currently, there is no way to know when a settings is never used. This would be useful information in case a settings is misspelled. This may be more complicated than it is worth.

Plan:

- [ ] Terra settings class will have to have a map added to it, this map will set a bit to 1 whenever a particular field is access. This will have to be through the . and [] operator, and will have to exclude operations like dumping/serializing.
- [ ] This map has to be serializable.
- [ ] The map has to be able to be "logical or" merged with another map
- [ ] When settings is passed on to a service, the service will have to track what it uses, and return the map to the main workflow (Is this practical?)
- [ ] When a task is passed setting, same thing... This is the part where it may become impractical.

**Comment by andyneff** [comment]
Slightly related to #5

**Comment by andyneff** [comment]
@NoahRJohnson What if, instead of trying this "settings tracking" idea, we instead modify settings.configure, to detect when a settings is set which has no default value, and give a warning when that happens. I think that should accomplish the same things of "You mispelled a setting in your config.json" file

```
warning(f'Setting {name} set but had no default. It is possible this is the wrong setting name')
```

This would also catch a setting that gets spelled wrong when it is used, assuming it doesn't match the name in the defaults

**Comment by NoahRJohnson** [comment]
That seems like a great idea.
